#!/usr/bin/with-contenv bash

# Enter our working directory
cd /fevr

# Check if Virtual Environment is initialized
[ ! -d "/fevr/venv" ] && \
    echo "Initializing Virtual Environment" && \
    python -m venv venv

# Activate Virtual Environment
echo "Starting Virtual Environment" && \
source /fevr/venv/bin/activate \

# Install Dependencies
echo "pip install wheel" && \
pip install wheel && \
echo "pip install requirements" && \
pip install -r /fevr/requirements.txt && \
echo "Done Installing python requirements"

echo "Starting fEVR"
# Uncomment to put fEVR into development Mode
#export FLASK_ENV='development'
/fevr/venv/bin/flask run -h "0.0.0.0" -p ${FEVR_PORT:-5090}