#!/usr/bin/with-contenv bash

# Enter our working directory
cd /fevr

# Make sure /fevr has the right permissions
chown -R 1000:1000 /fevr
# Check if Virtual Environment is initialized
echo "Python Virtual Environment already installed."
echo "Activating Python Virtual Environment"
source /fevr/venv/bin/activate

FEVR_HOST=${FEVR_HOST:-0.0.0.0}
FEVR_PORT=${FEVR_PORT:-5090}

FEVR_DEVELOPMENT=${FEVR_DEVELOPMENT}
if [ $FEVR_DEVELOPMENT="true"]; then
    export FLASK_ENV='development'
    /fevr/venv/bin/flask run -h "0.0.0.0" -p $FEVR_PORT
else
    export UWSGI_STARTING=1
    UWSGI_WORKERS=${UWSGI_WORKERS:-4}
    echo "Starting fEVR on $FEVR_HOST:$FEVR_PORT with $UWSGI_WORKERS workers."
    uwsgi --http $FEVR_HOST:$FEVR_PORT --workers $UWSGI_WORKERS --ini uwsgi.ini
fi