kind: pipeline
name: default
image_pull_secrets:
  - docker-auth-beardedtek.com
trigger:
  branch:
    - main
  event:
    - push
    - tag
steps:
- name: ghcr-io-TAG
  image: plugins/docker
  when:
    event:
      - tag
  settings:
    username: beardedtek
    password:
      from_secret: github_user_token
    repo: ghcr.io/beardedtek-com/fevr
    registry: ghcr.io
    tags: latest,${DRONE_TAG}
    experimental: true
    compress: true
    squash: true
- name: dockerhub-TAG
  image: plugins/docker
  when:
    event:
      - tag
  settings:
    username: beardedtek
    password:
      from_secret: docker_password
    repo: beardedtek/fevr
    tags: latest,${DRONE_TAG}
    experimental: true
    compress: true
    squash: true
    
- name: beardedtek-PUSH
  image: plugins/docker
  when:
    event:
      - push
  settings:
    username: beardedtek
    password:
      from_secret: docker_password
    repo: docker.beardedtek.com/beardedtek/fevr
    registry: docker.beardedtek.com
    tags: latest,${DRONE_REPO_BRANCH}
    experimental: true
    compress: true
    squash: true