kind: pipeline
name: default
image_pull_secrets:
  - docker-auth-beardedtek.com
trigger:
  branch:
    - 0.7-dev
  event:
    - push
steps:
- name: beardedtek-PUSH
  image: plugins/docker
  when:
    event:
      - push
  settings:
    username: beardedtek
    password:
      from_secret: docker_password
    repo: docker.beardedtek.com/beardedtek/fevr
    registry: docker.beardedtek.com
    tags: 0.7-dev
    experimental: true
    compress: true
    squash: true
