version: '3'
services:
  fevr:
    image: ghcr.io/beardedtek-com/fevr-standalone:main
    container_name: fevr-alpine
    restart: unless-stopped
    ports:
      - '8001:8001'
      - '8002:8002'
    volumes:
     - ./data/db:/var/www/db ##OPTIONAL: save database file
     - ./data/config:/var/www/config ##OPTIONAL: save config file locally
     - ./data/events:/var/www/html/events ##OPTIONAL: save events to a local folder
# Uncomment the following to map to an NFS share
#     - nfsvolume:/var/www/html/events ##OPTIONAL: save events to an NFS volume
#volumes:
#  nfsvolume:
#    driver_opts:
#      type: "nfs"
#      o: "addr=<your_nas_ip>,nfsvers=4" # Make sure to change to your NFS server's address
#     # o: "addr=<your_nas_ip>,rw,nfsvers=4" < SOME NFS SHARES REQUIRE THIS!!!
#      device: ":/path/to/your/nfs/share"
