version: '3'
services:
  fevr:
    image: beardedtek/fevr-standalone:alpine
    container_name: fevr-alpine
    restart: unless-stopped
    ports:
      - '8003:8001'
      - '8004:8002'
    volumes:
      - alpinenas:/nas

volumes:
  alpinenas:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.240,nfsvers=4"
      device: ":/export/files"
