version: '2.4'
services:
  fevr:
    image: ghcr.io/beardedtek-com/fevr:0.6
    container_name: fevr
    restart: unless-stopped
    privileged: true
    ports:
      - 5090:${FEVR_PORT:-5090}
    volumes:
      - ./events:/fevr/app/static/events
      - ./data:/fevr/app/data
      - ./varlib:/var/lib
      - ./config.yml:/fevr/app/data/config:ro
    environment:
      FEVR_DEVELOPMENT: ${FEVR_DEVELOPMENT:-false}
      FEVR_URL: ${FEVR_URL}
      FEVR_PORT: ${FEVR_PORT}
      TAILSCALE_ENABLE: ${TAILSCALE_ENABLE:-true}
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-fevr}
      TAILSCALE_TAGS: ${TAILSCALE_TAGS}
      MQTT_BROKER: ${MQTT_BROKER:-mqtt}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      MQTT_BROKER_USER: ${MQTT_BROKER_USER}
      MQTT_BROKER_PASSWORD: ${MQTT_BROKER_PASSWORD}
      MQTT_TOPICS: ${MQTT_TOPICS:-frigate/+}
      MQTT_VERBOSE_LOGGING: ${MQTT_VERBOSE_LOGGING:-true}
      MQTT_APIAUTH_KEY: ${MQTT_APIAUTH_KEY}
