version: '2.4'
services:
  fevr:
    image: ghcr.io/beardedtek-com/fevr:main
    container_name: fevr
    restart: unless-stopped
    privileged: true
    volumes:
      - ./:/fevr
    environment:
      FLASK_ENV: ${FLASK_ENV:-development}
      FEVR_PORT: ${FEVR_PORT:-5090}

      TAILSCALE_ENABLE: ${TAILSCALE_ENABLE:-true}
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-fevr}
      TAILSCALE_TAGS: ${TAILSCALE_TAGS}
      MQTT_BROKER_IP: ${MQTT_BROKER_IP}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      MQTT_BROKER_USER: ${MQTT_BROKER_USER}
      MQTT_BROKER_PASS: ${MQTT_BROKER_PASS}
      MQTT_TOPICS: ${MQTT_TOPICS}
