#!/bin/bash
# This will check if run_mqtt_client.sh has been generated.
# If it has not, we will check every 5 seconds
# After 120 seconds of checking (24 cycles) we will output an error msg
# telling the user to run the configuration
if [ -f "/fevr/run_mqtt_client.sh" ]; then
    echo "EXISTS, SKIPPING LOOP"
    EXISTS=1
else
    echo "DOES NOT EXIST, LOOPING"
    EXISTS=0
    echo "EXISTS = $EXISTS"
fi
while [ "$EXITS" != "1" ] # Loop until EXISTS = 1
do
    echo "LOOP"
    # Print URL to visit to configure fEVR
    echo "Visit $(hostname -i):5180/setup to complete setup."
    for i in {1..60}
    # Loop 24 times
    do
    # Check if /fevr/run_mqtt_client.sh exists
    # If it exists, set EXISTS to 1
    if [ -f "/fevr/run_mqtt_client.sh" ]; then
        echo "File Exists"
        EXISTS=1
        break
    fi
    # Wait 5 seconds (60*5 = 300 seconds or every 5 minutes)
    sleep 5
    done
    if [ "$EXISTS" == "1" ]; then
        break
    fi
done




chmod +x /fevr/run_mqtt_client.sh
/fevr/run_mqtt_client.sh