#!/usr/bin/python

# Define config.json contents via dict
config = {}
config['fevr'] = {}
config['frigate'] = {}
config['fevr']['base'] = "/var/www/"
config['fevr']['db'] = "/var/www/db/fEVR.sqlite"
config['fevr']['debug'] = "true"
config['fevr']['html'] = "/var/www/html"
config['fevr']['title'] = "My Home"
config['frigate']['apiEventPath'] = "/api/events/"
config['frigate']['clipPath'] = "/clip.mp4"
config['frigate']['snapPath'] = "/snapshot.jpg"
config['frigate']['url'] = "http://frigate.local:5000"

# setup command line arguments
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('debug', type=str)
parser.add_argument('title', type=str)
parser.add_argument('frigate', type=str)
args = parser.parse_args()

# change values according to user input
config['fevr']['debug'] = args.debug
config['fevr']['title'] = args.title
config['frigate']['url'] = args.frigate

# write config.json to file
with open("/var/www/config/config.json", "w+") as file:
    import json
    file.write(json.dumps(config, indent=2,sort_keys=True))
n=0

# Check if database exsists (and at least the size of the blank.sqlite)
from os.path import exists
if exists(config['fevr']['db']):
    from os.path import getsize
    if getsize(config['fevr']['db']) >= 24576:
        dbExists = True
else:
    from shutil import copy
    if exists(config['fevr']['db']):
        copy(config['fevr']['db'],f"{config['fevr']['db']}.BAK")
    from os import chown
    copy("/var/www/default/fEVR.sqlite",config['fevr']['db'])
    chown(config['fevr']['db'],100,101)

while n==0:
    from time import sleep
    sleep(86400)