#!/bin/bash
#
# If passed with no arguments, environment variables will be used.
# providing any options override environment variables
#usage: mqtt_client [-h] [-H HOST] [-p PORT] [-t TOPICS] [-u USER] [-P PASSWORD]
#
#optional arguments:
#  -h, --help            show this help message and exit
#  -H HOST, --host HOST
#  -p PORT, --port PORT
#  -t TOPICS, --topics TOPICS
#  -u USER, --user USER
#  -P PASSWORD, --password PASSWORD

/opt/fevr/startup/mqtt_client