#!/usr/bin/with-contenv bash
# This will check if run_mqtt_client.sh has been generated.
# If it has not, we will check every 5 seconds
# After 300 seconds of checking (60 cycles) we will output an error msg
# telling the user to run the configuration
while :; do
    if [ -f "/fevr/app/data/config.json" ]; then
        /fevr/venv/bin/python /fevr/app/mqtt_client -c "/fevr/app/data/config.json"
    fi
done
