#!/usr/bin/with-contenv bash
# This will check if run_mqtt_client.sh has been generated.
# If it has not, we will check every 5 seconds
# After 300 seconds of checking (60 cycles) we will output an error msg
# telling the user to run the configuration
if [ -f "/fevr/run_mqtt_client.sh" ]; then
    EXISTS=1
else
    EXISTS=0
fi
# Wait until UWSGI is started
sleep 60
while [ "$EXITS" != "1" ] # Loop until EXISTS = 1
do
    # Print URL to visit to configure fEVR
    echo ""
    echo ""
    echo "########################  SETUP NOT COMPLETE  ##################################"
    echo "#                                                                              #"
    echo "# fEVR will not function as intended until you complete this process           #"
    echo "# Please finish setup by visiting:                                             #"
    echo "# http://$(hostname -i):${FEVR_PORT:-5090}/setup.                                                #"
    echo "#                                                                              #"
    echo "################################################################################"
    echo ""
    echo ""
    for i in {1..60}
    # Loop 24 times
    do
    # Check if /fevr/run_mqtt_client.sh exists
    # If it exists, set EXISTS to 1
    if [ -f "/fevr/run_mqtt_client.sh" ]; then
        EXISTS=1
        break
    fi
    # Wait 5 seconds (60*5 = 300 seconds or every 5 minutes)
    sleep 5
    done
    if [ "$EXISTS" == "1" ]; then
        break
    fi
done

chmod +x /fevr/run_mqtt_client.sh
/fevr/run_mqtt_client.sh