#!/usr/bin/with-contenv bash
#    This code is a portion of frigate Event Video Recorder (fEVR)
#
#    Copyright (C) 2021-2022  The Bearded Tek (http://www.beardedtek.com) William Kenny
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU AfferoGeneral Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ ${TAILSCALE_ENABLE} ]; then
    # Get local docker network to forward so all containers are accessible via tailscale

    if [ ! $TAILSCALE_ADVERTISE_ROUTE ]; then
        TAILSCALE_ADVERTISE_ROUTE=$(getnetwork)
    fi
    # Enable IP forwarding
    rm -f /etc/sysctl.conf
    touch /etc/sysctl.conf
    echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.conf 2> /dev/null
    echo 'net.ipv6.conf.all.forwarding = 1' | tee -a /etc/sysctl.conf 2> /dev/null
    sysctl -p /etc/sysctl.conf
    
     #Start tailscaled
    tailscaled &

    # Wait until tailscaled is up...
    OK=1
    while [ $OK != 0 ]; do
        if ps | grep tailscaled | > /tmp/test.txt; then OK=0; else OK=1; fi
    done

    # Bring up tailscale
    tailscale up --authkey="${TAILSCALE_AUTHKEY}" \
                 --advertise-routes=${TAILSCALE_ADVERTISE_ROUTE} \
                 --hostname=${TAILSCALE_HOSTNAME:-fEVR} \
                 --advertise-tags=${TAILSCALE_TAGS} \
                 --accept-routes \
                 --exit-node=${TAILSCALE_EXIT_NODE} \
                 --accept-dns \
                 --reset

    # Run a loop to make sure it doesn't exit out.  Will expand here more eventually
    TS=0
    while [ $TS == 0 ]; do
        if [[ ! $(ip a show tailscale0 up | grep inet) ]] ;then
            tailscale up --authkey="${TAILSCALE_AUTHKEY}" \
                         --advertise-routes=${TAILSCALE_ADVERTISE_ROUTE} \
                         --hostname=${TAILSCALE_HOSTNAME:-fEVR} \
                         --advertise-tags=${TAILSCALE_TAGS} \
                         --accept-routes \
                         --exit-node=${TAILSCALE_EXIT_NODE} \
                         --accept-dns \
                         --reset
        fi
        sleep 30s
    done
fi
