#!/usr/bin/with-contenv bash
whoami
env
echo ""
echo ""
echo ""
echo "$TAILSCALE_ENABLE"
if [ "$TAILSCALE_ENABLE" == "false" ]; then
    FOREVER=1
    while [ $FOREVER == 1 ]; do
        sleep 9999999
    done
else
    echo "##### TAILSCALE ENABLED #####"
    # Enable IP forwarding
    rm -f /etc/sysctl.conf
    touch /etc/sysctl.conf
    echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.conf 2> /dev/null
    echo 'net.ipv6.conf.all.forwarding = 1' | tee -a /etc/sysctl.conf 2> /dev/null
    sysctl -p /etc/sysctl.conf

    # Start tailscaled
    apk add tailscale
    echo "##### STARTING TAILSCALED #####"
    tailscaled &

    # While loop to make sure tailscaled has started
    tailscale_status=""
    OK=1
    while [ $OK != 0 ]; do
        if ps ef | grep tailscaled | > /tmp/test.txt; then OK=0; else OK=1; fi
    done

    echo "##### BRINGING UP TAILSCALE #####"
    echo "##### tags:"
    echo $TAILSCALE_TAGS
    echo "##### hostname:"
    echo $TAILSCALE_HOSTNAME
    echo "##### auth_key:"
    echo TAILSCALE_AUTHKEY
    tailscale up --authkey="$TAILSCALE_AUTHKEY" --accept-routes --accept-dns --hostname "$TAILSCALE_HOSTNAME" --advertise-tags=$TAILSCALE_TAGS
    TS=0
    while [ $TS == 0 ]; do
        sleep 5000
    done
fi