#!/bin/bash

# Get Environment Variable and set defaults if they're not set
SQLW_START="${SQLITE_WEB_ENABLE:-true}"
SQLW_PORT="${SQLITE_WEB_PORT:-5081}"
IP_ADDR_EXT=$(ip a | grep inet| grep -v "127.0.0.1" | awk '{print $2;}' | cut -d/ -f1) \
IP_ADDR="${IP_ADDR_EXT:-192.168.204.1}"
echo ""
echo ""
echo "      Starting sqlite web at http://$IP_ADDR:$SQLW_PORT"
echo ""
echo ""

if "$SQLW_START" == "true"; then
    sqlite_web -p "$SQLW_PORT" -H 0.0.0.0 -x /var/www/data/db/fEVR.sqlite
    echo "sqlite_web running on port $SQLWPORT".
else
    echo "sqlite_web disabled. Set env var SQLITE_WEB_ENABLE='true' to enable."
fi